// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBmzCRZRmz6p4pkCZ9IuoI2sktZodu-UeE",
      authDomain: "emindmatterssystem.firebaseapp.com",
      projectId: "emindmatterssystem",
      storageBucket: "emindmatterssystem.appspot.com",
      messagingSenderId: "622099708370",
      appId: "1:622099708370:web:292f1f4217c8349ab1700b",
      measurementId: "G-9G7BHKBGM8"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyBmzCRZRmz6p4pkCZ9IuoI2sktZodu-UeE",
      authDomain: "emindmatterssystem.firebaseapp.com",
      projectId: "emindmatterssystem",
      storageBucket: "emindmatterssystem.appspot.com",
      messagingSenderId: "622099708370",
      appId: "1:622099708370:web:292f1f4217c8349ab1700b",
      measurementId: "G-9G7BHKBGM8"
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyBmzCRZRmz6p4pkCZ9IuoI2sktZodu-UeE",
      authDomain: "emindmatterssystem.firebaseapp.com",
      projectId: "emindmatterssystem",
      storageBucket: "emindmatterssystem.appspot.com",
      messagingSenderId: "622099708370",
      appId: "1:622099708370:web:292f1f4217c8349ab1700b",
      measurementId: "G-9G7BHKBGM8"
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBmzCRZRmz6p4pkCZ9IuoI2sktZodu-UeE",
    authDomain: "emindmatterssystem.firebaseapp.com",
    projectId: "emindmatterssystem",
    storageBucket: "emindmatterssystem.appspot.com",
    messagingSenderId: "622099708370",
    appId: "1:622099708370:web:292f1f4217c8349ab1700b",
    measurementId: "G-9G7BHKBGM8"
  );
}
